branches:
  except:
  - master
  - development
sudo: required
language: generic
services:
  - docker
script:
  - sh -x ./build-with-docker.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "travis-bot@clarin.eu"
deploy:
  api_key:
    secure: "$DEPLOY_OAUTH_TOKEN"
  file: "target/CLRSwitchboard-${TRAVIS_TAG}.tgz"
  on:
    tags: true
  overwrite: true
  provider: releases
  skip_cleanup: true
notifications:
  email:
    on_success: change
    on_failure: never