language: generic
dist: xenial
os: linux
addons:
  apt:
    packages:
      - bsdtar
      - cmake
services:
  - docker
script:
  - make package
  - cp build/switchboard.tar.gz build/switchboard-${TRAVIS_TAG}.tar.gz
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "travis-bot@clarin.eu"
deploy:
  token: $DEPLOY_OAUTH_TOKEN
  file: "build/switchboard-${TRAVIS_TAG}.tar.gz"
  on:
    tags: true
  overwrite: true
  provider: releases
notifications:
  email:
    on_success: change
    on_failure: never