server:
    applicationContextPath: ${APP_CONTEXT_PATH:-/}
    applicationConnectors:
        - type: http
          port: 8080
          # time before the request expires
          idleTimeout: 180 seconds
    adminConnectors:
        - type: http
          port: 8089

logging:
    level: INFO
    loggers:
        "eu.clarin": DEBUG

switchboard:
    tikaConfigPath: ./tikaConfig.xml
    contactEmail: switchboard@clarin.eu
    tools:
        toolRegistryPath: ../../switchboard-tool-registry
        showOnlyProductionTools: false
    dataStore:
        location: # e.g. /my/data; defaults to temporary storage
        eraseAllStorageOnStart: false
        maxSize: 5M
        maxLifetime: 2
        maxLifetimeUnit: hours
        cleanupPeriod: 13
        cleanupPeriodUnit: minutes
    urlResolver:
        connectTimeout: 3
        readTimeout: 3
        unit: seconds
