server:
    applicationContextPath: ${HTTP_CONTEXT_PATH:-/}
    applicationConnectors:
        - type: http
          port: 8080
          # time before the request expires
          idleTimeout: 180 seconds
    adminConnectors:
        - type: http
          port: 8089

logging:
    level: INFO
    loggers:
        "eu.clarin": ${LOG_LEVEL:-DEBUG}

switchboard:
    tikaConfigPath: ./tikaConfig.xml
    contactEmail: ${CONTACT_EMAIL:-switchboard@clarin.eu}
    tools:
        toolRegistryPath: ${REGISTRY_TOOL_PATH:-../../switchboard-tool-registry/tools}
        logoRegistryPath: ${REGISTRY_LOGO_PATH:-../../switchboard-tool-registry/logos}
        showOnlyProductionTools: ${REGISTRY_PRODUCTIONTOOLS_ONLY:-false}
        enableMultipleResources: ${ENABLE_MULTIPLE_RESOURCES:-false}
    dataStore:
        location: # e.g. /my/data; defaults to temporary storage
        eraseAllStorageOnStart: ${DATASTORE_STARTERASE:-false}
        maxSize: ${DATASTORE_MAX_FILESIZE:-5M}
        maxFiles: ${DATASTORE_MAX_FILES:-10k}
        maxLifetime: ${DATASTORE_MAX_FILELT:-2}
        maxLifetimeUnit: ${DATASTORE_FILELT_UNIT:-hours}
        cleanupPeriod: ${DATASTORE_CLEANPERIOD:-13}
        cleanupPeriodUnit: ${DATASTORE_CLEANPERIOD_UNIT:-minutes}
    urlResolver:
        # preflight = used for the preflight API, see
        #   https://github.com/clarin-eric/switchboard-doc/blob/master/documentation/IntegrationProvider.md#preflight-api
        preflightConnectTimeout: ${URLRESOLVER_PREFLIGHT_CONNECTTIMEOUT:-1}
        preflightReadTimeout: ${URLRESOLVER_PREFLIGHT_READTIMEOUT:-1}
        preflightDataLimit: ${URLRESOLVER_PREFLIGHT_DATALIMIT:-8192}
        # connectTimeout is also used both as a socket connection timeout and
        #   also as a timeout for the http client library, until it can provide
        #   a thread for the request; 0 is infinite
        connectTimeout: ${URLRESOLVER_CONNECTTIMEOUT:-3}
        readTimeout: ${URLRESOLVER_READTIMEOUT:-3}
        unit: ${URLRESOLVER_TIMEOUT_UNIT:-seconds}
        maxHttpCacheEntries: ${URLRESOLVER_MAX_HTTPCACHE_ENTRIES:-256}
    showFundingBadge: ${SHOW_FUNDING_BADGE:-false}
