server:
  applicationContextPath: ${APP_CONTEXT_PATH:-/}
  applicationConnectors:
    - type: http
      port: 8088
      # time before the request expires
      idleTimeout: 180 seconds
  adminConnectors:
    - type: http
      port: 8089

logging:
  level: INFO
  loggers:
    "eu.clarin": DEBUG

switchboard:
  tikaConfigPath: ./src/main/resources/tikaConfig.xml
  toolRegistryPath: ../../switchboard-tool-registry
  dataStore:
    location: # e.g. /my/data; defaults to temporary storage
    eraseAllStorageOnStart: false
    maxSize: 5M
    maxLifetime: 2
    maxLifetimeUnit: hours
    cleanupPeriod: 13
    cleanupPeriodUnit: minutes
