# -------------------------------------------
# Time-stamp: <2018-03-01 15:00:55 (zinn)>
# -------------------------------------------
# C. Zinn
#
#
# A local nextcloud instance is used as file storage server for the switchboard
# Example file for wonderfull/nextcloud image is given below.
# You need to adapt the file names (see volumes) to fit your needs!
#
# 1. docker-compose pull
# 2. docker-compose up -d nextcloud-db
# 3. sleep 15
# 4. docker-compose up -d
# Note that a theme (such as b2drop can be copied into themes,
# and that an app (such as lrswitchboardbridge) can be copied into apps (must be enabled by admin)

nextcloud:
  image: wonderfall/nextcloud
  ports:
    - 8088:8888      
  links:
    - nextcloud-db:nextcloud-db   
  environment:
    - UID=1000
    - GID=1000
    - UPLOAD_MAX_SIZE=10G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - CRON_PERIOD=15m
    - TZ=Europe/Berlin
    - ADMIN_USER=admin            # Don't set to configure through browser
    - ADMIN_PASSWORD=admin        # Don't set to configure through browser
    - DOMAIN=localhost
    - DB_TYPE=mysql
    - DB_NAME=nextcloud
    - DB_USER=nextcloud
    - DB_PASSWORD=supersecretpassword
    - DB_HOST=nextcloud-db
  volumes:
    - /Users/zinn/wonderfall-nextcloud/mnt/nextcloud/data:/data
    - /Users/zinn/wonderfall-nextcloud/mnt/nextcloud/config:/config
    - /Users/zinn/wonderfall-nextcloud/mnt/nextcloud/apps:/apps2
    - /Users/zinn/wonderfall-nextcloud/mnt/nextcloud/themes:/nextcloud/themes

nextcloud-db:
  image: mariadb:latest
  volumes:
    - /Users/zinn/wonderfall-nextcloud/mnt/nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=supersecretpassword
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=supersecretpassword

