name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
  - cron: "23 4 12 * *"
jobs:
  prepare:
    name: "Prepare"
    runs-on: ubuntu-22.04
    steps:
      - name: Get the version
        id: set_version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Check create release for tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        id: check_release
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.version }}"
          StatusCode=$(curl -o -I -L -s -w "%{http_code}" -X GET -G $URL)
          if [ "$StatusCode" == 200 ]; then
            echo "Release exists"
            echo "create_release=false" >> $GITHUB_ENV
          else
            echo "Release does not exist"
            echo "create_release=true" >> $GITHUB_ENV
          fi
  build:
    name: "Build"
    needs: [prepare]
    # Run job for: github releases, tag pushes without github release and regular pushes (not tag)
    if: github.event_name == 'release' || !contains(github.ref, 'refs/tags/') || env.create_release == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Build
        run: |
          make build-docker-image
          docker save switchboard/switchboard:latest > switchboard-docker-image.tar
        env:
          CI_VERSION: ${{ env.version }}
      - name: Upload exported docker image
        uses: actions/upload-artifact@v3
        with:
          name: switchboard-docker-image
          path: switchboard-docker-image.tar
          retention-days: 1
  test-ui:
    name: "Test UI"
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      - name: Download docker image from build job
        uses: actions/download-artifact@v3
        with:
          name: switchboard-docker-image
      - name: 'Fetch tools'
        uses: actions/checkout@v3
        with:
          repository: clarin-eric/switchboard-tool-registry
          ref: production
          fetch-depth: '1'
          path: switchboard-tool-registry
      - name: Test UI
        run: |
          docker load < switchboard-docker-image.tar
          SWITCHBOARD_TOOL_REGISTRY_DIR=${GITHUB_WORKSPACE}/switchboard-tool-registry  test/run-end-to-end.sh
        env:
          CI_VERSION: ${{ env.version }}
  release:
    name: "Release"
    needs: [prepare, build, test-ui]
    # Run job for github releases and tag pushes (without github release)
    if: github.event_name == 'release' || env.create_release == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      - name: Download docker image from build job
        uses: actions/download-artifact@v3
        with:
          name: switchboard-docker-image
      - name: Make release package
        run: |
          docker load < switchboard-docker-image.tar
          make package
          cp build/switchboard.tar.gz switchboard-${{ env.version }}.tar.gz
      # For github releases -> upload release package to existing release
      # For tag pushes without github release -> create a github release with release package
      - name: Create prelease for this tag
        if: env.create_release == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: true
          prerelease: true
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Pseudo-ternary expression: get "upload_url" from the release created above, or from github "release" event if release is pre-created
          upload_url: ${{ env.create_release == 'true' && steps.create_release.outputs.upload_url || github.event.release.upload_url }} 
          asset_path: ./switchboard-${{ env.version }}.tar.gz
          asset_name: switchboard-${{ env.version }}.tar.gz
          asset_content_type: application/tar+gzip
      - uses: eregon/publish-release@v1
        if: env.create_release == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
